"""TSL property identifiers for /living/home/element/query (aligned with livolo-rest-api)."""

from __future__ import annotations

# Union of identifiers across Livolo product types — see livolo-rest-api/src/lib/property-identifiers.js
_ALL_RAW: list[str] = (
    [f"PowerSwitch_{i}" for i in range(1, 7)]
    + [
        "PowerSwitch",
        "SocketSwitch_1",
        "SocketSwitch_2",
        "SocketSwitch_3",
        "LightSwitch",
        "WorkSwitch",
        "on",
        "bri",
        "bri_2",
        "CurtainPosition",
        "CurtainOperation",
        "CurtainMode",
        "ChangeDirection",
        "ModeSettings",
        "PositionCalibrate",
        "PositionLimited",
        "powerstate",
        "Brightness",
        "brightness",
        "ColorTemperature",
        "colorTemperature",
        "HSVColor",
        "RGBMode",
        "CurrentTemperature",
        "CurrentFahrenheit",
        "CurrentHumidity",
        "TargetTemperature",
        "DevConfig",
        "ScreenMode",
        "TemperatureCalibrate",
        "Speed",
        "StatusReminder",
        "AlarmState",
        "MotionAlarmState",
        "DelayTime",
        "InitDelay",
        "SecondDelayTime",
        "MeasuredIlluminance",
        "MeasuredVoice",
        "VoiceMode",
        "alarm",
        "Alarm",
        "AlarmSwitch",
        "StatusLightSwitch",
        "DeviceSwitch",
        "MotionTrackStatus",
        "Gateway",
        "SocketPowerState",
        "AutoSocketSta",
        "RealTimePower",
        "Current",
        "CurrentVoltage",
        "UnitPowerConsumption",
        "Power",
        "Level",
        *[f"AnalogValue{i}" for i in range(1, 7)],
        "BinaryValue1",
        "SwitchStatus",
        "BaselineCurrent",
        "LoadCurrent",
        "WifiName",
        "MacAddress",
        "Version",
        "IPAddress",
        "SoftwareInfo",
        "BatteryPercentage",
        "Group",
        "Protocol",
        "Status",
        "Range",
        *[f"Sensitivity{i}" for i in range(1, 9)],
    ]
)

ALL_PROPERTY_IDENTIFIERS: list[str] = sorted(set(_ALL_RAW))
